version: '3.8'

services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile.node
    image: php74_node_app
    volumes:
      - .:/var/www
    networks:
      - mynetwork

  php_app:
    build:
      context: .
      dockerfile: Dockerfile.composer
    image: php81_composer_app
    volumes:
      - .:/var/www
    networks:
      - mynetwork

  webserver:
    image: arm64v8/nginx:latest
    ports:
      - "80:80"
      - "443:443"  # Assurez-vous que le port 443 est mappé
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ~/nginx/ssl:/etc/nginx/ssl  # Monte le dossier SSL depuis votre répertoire utilisateur

    networks:
      - mynetwork

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  dbdata:
